# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'VR_Gallery' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

pod 'MD360Player4iOS'
pod 'Masonry'
pod 'SDWebImage', '~>3.8'
pod 'MBProgressHUD'

  # Pods for VR_Gallery

end
